version: '3.8'

services:
  postgres_db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: doan_user
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: secure_file_sharing
    ports:
      - "5432:5432" # Ánh xạ port để bạn có thể dùng PgAdmin kết nối từ máy host
    volumes:
      - pgdata:/var/lib/postgresql/data # Lưu trữ dữ liệu DB bền vững
    networks:
      - secure_net

  ca_server:
    build:
      context: .
      dockerfile: ./ca_server/Dockerfile
    container_name: ca_server
    ports:
      - "5001:5001"
    volumes:
      - ./ca_server/root_ca:/app/root_ca
      - ./ca_server/intermediate_ca:/app/intermediate_ca
    networks:
      - secure_net

  auth_server:
    build:
      context: .
      dockerfile: ./auth_server/Dockerfile
    container_name: auth_server
    ports:
      - "5002:5002"
    # 2. CẬP NHẬT: Thêm biến môi trường kết nối DB
    environment:
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - DB_NAME=secure_file_sharing
      - DB_USER=doan_user
      - DB_PASS=123456
    volumes:
      - ./auth_server/auth_priv_key.pem:/app/auth_priv_key.pem
      - ./auth_server/auth_pub_key.pem:/app/auth_pub_key.pem
    depends_on:
      - ca_server
      - postgres_db # 3. Đảm bảo DB khởi động trước
    networks:
      - secure_net

  file_server:
    build:
      context: .
      dockerfile: ./file_server/Dockerfile
    container_name: file_server
    ports:
      - "5003:5003"
    # 4. CẬP NHẬT: Thêm biến môi trường kết nối DB
    environment:
      - DB_HOST=postgres_db
      - DB_PORT=5432
      - DB_NAME=secure_file_sharing
      - DB_USER=doan_user
      - DB_PASS=123456
    volumes:
      # BỎ ánh xạ file database vì đã dùng PostgreSQL
      - ./file_server/storage:/app/storage
      - ./file_server/logs:/app/logs
    depends_on:
      - auth_server
      - postgres_db # 5. Đảm bảo DB khởi động trước
    networks:
      - secure_net

# Khai báo volume dùng chung cho PostgreSQL
volumes:
  pgdata:

networks:
  secure_net:
    driver: bridge